/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "JavAmazon"
include(":inventory")
include(":payment")
include(":order")
include(":cart")
include(":catalog")
include(":notification")
include(":common")
include(":search")
