/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":common"))
    testImplementation(libs.junit.jupiter)
    testImplementation(libs.assertj)
}

description = "cart"
