/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":common"))
    api(project(":shared"))
    implementation(libs.spring.boot.starter.web)
    implementation(libs.flyway)
    implementation(libs.flyway.postgres)
    runtimeOnly(libs.postgresql)
}

description = "catalog"
