/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    id("org.springframework.boot")
}

repositories {
    mavenCentral()
}

group = "tech.reactiv.ecommerce"
version = "0.0.1"
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

dependencies {
    implementation(platform(org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES))
    "testRuntimeOnly"("org.junit.platform:junit-platform-launcher")
}

tasks.withType<Test> {
    useJUnitPlatform()
}
