/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
}

repositories {
    mavenCentral()
}

group = "tech.reactiv.ecommerce"
version = "0.0.1"
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}
