/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    implementation(platform(libs.opentelemetry.bom))
    implementation("io.opentelemetry:opentelemetry-api")
    testImplementation("io.opentelemetry:opentelemetry-sdk")
    testImplementation("io.opentelemetry:opentelemetry-exporter-logging")
    testImplementation(libs.junit.jupiter)
    testImplementation(libs.assertj)
}

description = "common"
